const commonStyles = {
  container: {
    padding: "20px",
    maxWidth: "600px",
    margin: "20px auto",
    display: "flex",
    flexDirection: "column",
    fontFamily: "'Nunito', sans-serif",
    textAlign: "center",
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    boxShadow: "0px 5px 20px rgba(0, 0, 0, 0.15)",
    // Responsive
    "@media (max-width: 768px)": {
      padding: "15px",
      margin: "15px auto",
    },
    "@media (max-width: 480px)": {
      padding: "10px",
      margin: "10px auto",
      borderRadius: "4px",
    },
  },
  fullWidthContainer: {
    padding: "20px",
    width: "100%",
    maxWidth: "100%",
    margin: "0",
    display: "flex",
    flexDirection: "column",
    fontFamily: "'Nunito', sans-serif",
    textAlign: "center",
    backgroundColor: "#ffffff",
    // Responsive
    "@media (max-width: 768px)": {
      padding: "15px",
    },
    "@media (max-width: 480px)": {
      padding: "10px",
    },
  },
  banner: {
    width: "100%",
    height: "300px",
    backgroundSize: "cover",
    backgroundPosition: "center",
    borderRadius: "10px",
    // Responsive
    "@media (max-width: 768px)": {
      height: "200px",
      borderRadius: "8px",
    },
    "@media (max-width: 480px)": {
      height: "150px",
      borderRadius: "4px",
    },
  },
  bannerImage: {
    width: "100%",
    height: "300px",
    objectFit: "cover",
    borderRadius: "10px",
    // Responsive
    "@media (max-width: 768px)": {
      height: "200px",
      borderRadius: "8px",
    },
    "@media (max-width: 480px)": {
      height: "150px",
      borderRadius: "4px",
    },
  },
  logoContainer: {
    display: "flex",
    justifyContent: "center",
    marginTop: "-50px",
    cursor: "pointer",
  },
  logo: {
    width: "90px",
    height: "90px",
    borderRadius: "50%",
    border: "4px solid white",
    boxShadow: "0px 4px 6px rgba(0,0,0,0.2)",
  },
  backButton: {
    backgroundColor: "#007bff",
    width:"110px",
    color: "#fff",
    border: "none",
    padding: "10px 20px",
    borderRadius: "8px",
    cursor: "pointer",
    marginBottom: "20px",
    textAlign: "center",
  },
  backButtonLink: {
    backgroundColor: "#007bff",
    width:"200px",
    color: "#fff",
    border: "none",
    padding: "10px 10px",
    borderRadius: "8px",
    cursor: "pointer",
    marginBottom: "20px",
    textAlign: "center",
    textDecoration: "none",
  },
  indigoButton: {
    backgroundColor: '#4F46E5',
    color: "#fff",
    border: "none",
    padding: "10px 20px",
    borderRadius: "8px",
    cursor: "pointer",
    marginBottom: "20px",
    textAlign: "center",
    textDecoration: "none",
  },
  greenButton: {
    backgroundColor: '#188c1c',
    color: "#fff",
    border: "none",
    padding: "10px 20px",
    borderRadius: "8px",
    cursor: "pointer",
    marginBottom: "20px",
    textAlign: "center",
    textDecoration: "none",
  },
  orangeButton: {
    backgroundColor: '#F59E0B',
    color: "#fff",
    border: "none",
    padding: "10px 20px",
    borderRadius: "8px",
    cursor: "pointer",
    marginBottom: "20px",
    textAlign: "center",
    textDecoration: "none",
  },
  redButton: {
    backgroundColor: '#EF4444',
    color: "#fff",
    border: "none",
    padding: "10px 20px",
    borderRadius: "8px",
    cursor: "pointer",
    marginBottom: "20px",
    textAlign: "center",
    textDecoration: "none",
  },
  topBorder: {
    borderTop: "2px solid #e7e7e7",
    paddingTop:"20px"
  },
  editButton: {
    backgroundColor: "#4F46E5",
    width:"100%",
    color: "#fff",
    border: "none",
    padding: "10px 20px",
    borderRadius: "8px",
    cursor: "pointer",
    marginBottom: "20px",
    textAlign: "center",
  },
  logoutButton: {
    backgroundColor: "#007bff",
    width:"150px",
    color: "#fff",
    border: "none",
    padding: "10px 20px",
    borderRadius: "5px",
    cursor: "pointer",
    marginBottom: "20px",
    textAlign: "center",
  },
  addButton: {
    backgroundColor: "#007bff",
    width:"100%",
    color: "#fff",
    border: "none",
    padding: "10px 20px",
    borderRadius: "8px",
    cursor: "pointer",
    marginBottom: "20px",
    textAlign: "center",
  },
  confirmButton: {
    backgroundColor: "#53bf49",
    width:"100%",
    color: "#fff",
    border: "none",
    padding: "10px 20px",
    borderRadius: "8px",
    cursor: "pointer",
    textAlign: "center",
  },
  cancelButton: {
    backgroundColor: "#cc8733",
    width:"100%",
    color: "#fff",
    border: "none",
    padding: "10px 20px",
    borderRadius: "8px",
    cursor: "pointer",
    textAlign: "center",
  },
  title: {
    fontSize: "28px",
    fontWeight: "700",
    color: "#1f262e",
    // Responsive
    "@media (max-width: 768px)": {
      fontSize: "24px",
    },
    "@media (max-width: 480px)": {
      fontSize: "20px",
    },
  },
  subTitle: {
    fontSize: "22px",
    fontWeight: "600",
    color: "#48596b",
    // Responsive
    "@media (max-width: 768px)": {
      fontSize: "20px",
    },
    "@media (max-width: 480px)": {
      fontSize: "18px",
    },
  },
  sectionContainer: {
    padding: "15px",
    backgroundColor: "#f9f9f9",
    borderRadius: "10px",
    marginTop: "10px",
    textAlign: "left",
  },
  fullPageLoader: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    backgroundColor: "#ffffff",
  },
  chatContainer: {
    flex: 1,
    overflowY: "auto",
    marginBottom: "20px",
    padding: "10px",
    backgroundColor: "#f8f8f8",
    borderRadius: "5px",
  },
  message: {
    padding: "10px",
    margin: "10px 0",
    backgroundColor: "#e9ecef",
    borderRadius: "5px",
  },
  inputContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  input: {
    flex: 1,
    padding: "10px",
    borderRadius: "5px",
    border: "1px solid #ccc",
    marginRight: "10px",
  },
  sendButton: {
    backgroundColor: "#007bff",
    color: "#fff",
    border: "none",
    padding: "10px 20px",
    borderRadius: "5px",
    cursor: "pointer",
  },
};

export default commonStyles;
