const habilidades = {
    "Tecnología": [
      "Desarrollo de software",
      "Programación en JavaScript",
      "Programación en Python",
      "Análisis de datos",
      "SEO (Optimización en motores de búsqueda)",
      "Edición de video",
      "Edición de fotografía",
      "Manejo de redes sociales",
      "Ciberseguridad",
      "Administración de bases de datos",
      "Computación en la nube",
      "Desarrollo web",
      "Diseño UX/UI",
      "Blockchain",
      "Automatización de procesos",
      "Redes y telecomunicaciones",
      "Programación en C++",
      "Programación en Java",
      "Desarrollo de inteligencia artificial",
      "Big Data",
      "Machine Learning",
      "Realidad aumentada",
      "Realidad virtual",
      "Robótica",
      "Desarrollo de videojuegos",
      "Seguridad informática",
      "Pruebas de software",
      "Desarrollo de aplicaciones móviles",
      "Administración de servidores",
      "Scripting con Bash",
      "Hacking ético",
      "Integración de APIs"
    ],
    "Comunicación": [
      "Comunicación escrita",
      "Comunicación verbal",
      "Escritura técnica",
      "Persuasión",
      "Escucha activa",
      "Habilidades interpersonales",
      "Manejo de conflictos",
      "Atención al cliente",
      "Oratoria",
      "Redacción de contenido",
      "Presentación de informes",
      "Storytelling",
      "Gestión de crisis",
      "Comunicación intercultural",
      "Gestión de comunidades",
      "Moderación de foros",
      "Narrativa digital"
    ],
    "Liderazgo": [
      "Liderazgo",
      "Gestión de proyectos",
      "Trabajo en equipo",
      "Resolución de problemas",
      "Toma de decisiones",
      "Capacidad de delegar",
      "Gestión del tiempo",
      "Visión estratégica",
      "Negociación",
      "Liderazgo transformacional",
      "Coaching empresarial",
      "Facilitación de reuniones",
      "Mentoría",
      "Manejo del estrés",
      "Ética profesional"
    ],
    "Creatividad y Diseño": [
      "Creatividad",
      "Innovación",
      "Pensamiento crítico",
      "Diseño gráfico",
      "Desarrollo de ideas",
      "Improvisación",
      "Estrategia de contenido",
      "Branding",
      "Ilustración digital",
      "Dibujo técnico",
      "Fotografía artística",
      "Diseño de moda",
      "Modelado 3D",
      "Edición de sonido",
      "Diseño de productos",
      "Composición musical"
    ],
    "Marketing y Ventas": [
      "Marketing digital",
      "Publicidad",
      "Manejo de redes sociales",
      "Ventas",
      "Copywriting",
      "Gestión de marca",
      "Planificación estratégica",
      "Atención al cliente",
      "Email marketing",
      "SEO avanzado",
      "Marketing de afiliados",
      "Estrategia de mercado",
      "Psicología del consumidor",
      "Análisis de competencia",
      "Marketing en redes sociales",
      "Marketing B2B",
      "Marketing de contenidos",
      "Publicidad en Google Ads",
      "Publicidad en Facebook Ads"
    ],
    "Habilidades Personales": [
      "Adaptabilidad",
      "Empatía",
      "Inteligencia emocional",
      "Responsabilidad",
      "Organización",
      "Capacidad de aprendizaje",
      "Multitarea",
      "Resiliencia",
      "Paciencia",
      "Autodisciplina",
      "Gestión del estrés",
      "Tolerancia a la frustración",
      "Pensamiento positivo",
      "Manejo del tiempo",
      "Escucha activa",
      "Trabajo bajo presión",
      "Networking",
      "Gestión del cambio"
    ],
    "Ciencias y Análisis": [
      "Investigación",
      "Habilidades analíticas",
      "Matemáticas",
      "Estadística",
      "Metodología científica",
      "Gestión de datos",
      "Modelado de datos",
      "Química",
      "Física",
      "Biotecnología",
      "Astrofísica",
      "Neurociencia",
      "Genética",
      "Ecología",
      "Biología molecular",
      "Ingeniería ambiental",
      "Geología"
    ],
    "Idiomas": [
      "Inglés",
      "Español",
      "Francés",
      "Alemán",
      "Mandarín",
      "Japonés",
      "Portugués",
      "Italiano",
      "Ruso",
      "Coreano",
      "Árabe",
      "Hindi",
      "Turco",
      "Neerlandés",
      "Hebreo",
      "Griego",
      "Sueco",
      "Danés",
      "Polaco",
      "Noruego",
      "Finlandés"
    ],
    "Finanzas y Contabilidad": [
      "Análisis financiero",
      "Contabilidad",
      "Gestión de presupuestos",
      "Auditoría financiera",
      "Planificación financiera",
      "Inversiones",
      "Gestión de riesgos",
      "Valoración de empresas",
      "Gestión de impuestos",
      "Mercados bursátiles",
      "Criptomonedas",
      "Cálculo financiero"
    ],
    "Salud y Bienestar": [
      "Nutrición",
      "Entrenamiento personal",
      "Técnicas de relajación",
      "Primeros auxilios",
      "Psicología clínica",
      "Terapias alternativas",
      "Medicina deportiva",
      "Cuidado de pacientes",
      "Enfermería",
      "Fisioterapia",
      "Yoga",
      "Mindfulness",
      "Terapia ocupacional",
      "Gestión del bienestar"
    ],
    "Habilidades Manuales y Oficios": [
      "Carpintería",
      "Electricidad",
      "Fontanería",
      "Reparación de automóviles",
      "Construcción",
      "Soldadura",
      "Instalación de sistemas de energía solar",
      "Restauración de muebles",
      "Cerámica",
      "Jardinería",
      "Agricultura ecológica",
      "Mecánica de bicicletas"
    ],
    "Logística y Transporte": [
      "Gestión de inventarios",
      "Transporte y distribución",
      "Optimización de rutas",
      "Logística internacional",
      "Gestión de almacenes",
      "Manejo de cadena de suministro",
      "Planificación de la demanda",
      "Coordinación de entregas",
      "Manejo de mercancías peligrosas"
    ]
  };
  
  export default habilidades;
  