const ocupaciones = [
  "Abogado",
  "Actor",
  "Administrador",
  "Agricultor",
  "Albañil",
  "Alfarero",
  "Analista de datos",
  "Analista financiero",
  "Antropólogo",
  "Apicultor",
  "Arquitecto",
  "Arqueólogo",
  "Artesano",
  "Artista",
  "Asesor financiero",
  "Asistente de vuelo",
  "Astrónomo",
  "Atleta profesional",
  "Auditor",
  "Autor",
  "Auxiliar de enfermería",
  "Auxiliar de farmacia",
  "Bailarín",
  "Banquero",
  "Barbero",
  "Bartender",
  "Biólogo",
  "Bombero",
  "Botánico",
  "Cajero",
  "Carpintero",
  "Cerrajero",
  "Chef",
  "Científico",
  "Cirujano",
  "Coach de vida",
  "Comerciante",
  "Compositor",
  "Conductor de autobús",
  "Conductor de tren",
  "Conserje",
  "Consultor",
  "Contador",
  "Corredor de bienes raíces",
  "Costurero",
  "Criador de animales",
  "Criminólogo",
  "Cuidadores de ancianos",
  "Decorador de interiores",
  "Dentista",
  "Deportista",
  "Detective",
  "Desarrollador de software",
  "Diseñador de interiores",
  "Diseñador gráfico",
  "Diseñador industrial",
  "Diseñador web",
  "Docente",
  "Doctor",
  "Economista",
  "Editor",
  "Electricista",
  "Emprendedor",
  "Enfermero",
  "Entrenador personal",
  "Escultor",
  "Escritor",
  "Esteticista",
  "Estilista",
  "Estudiante",
  "Farmacéutico",
  "Filósofo",
  "Físico",
  "Florista",
  "Fotógrafo",
  "Futbolista",
  "Ganadero",
  "Geólogo",
  "Gestor cultural",
  "Guía turístico",
  "Historiador",
  "Ingeniero agrónomo",
  "Ingeniero civil",
  "Ingeniero de alimentos",
  "Ingeniero de sistemas",
  "Ingeniero eléctrico",
  "Ingeniero industrial",
  "Ingeniero mecánico",
  "Ingeniero químico",
  "Instructor de yoga",
  "Intérprete",
  "Investigador",
  "Jardinero",
  "Joyero",
  "Locutor de radio",
  "Maestro de primaria",
  "Maestro de secundaria",
  "Maquillador",
  "Marinero",
  "Mecánico",
  "Médico general",
  "Meteorólogo",
  "Microbiólogo",
  "Minero",
  "Modelador 3D",
  "Modelista",
  "Modista",
  "Músico",
  "Neurocirujano",
  "Nutricionista",
  "Obrero",
  "Oceanógrafo",
  "Odontólogo",
  "Oftalmólogo",
  "Operador de maquinaria",
  "Organizador de eventos",
  "Ornitólogo",
  "Ortodontista",
  "Panadero",
  "Paramédico",
  "Parapsicólogo",
  "Pastelero",
  "Patólogo",
  "Periodista",
  "Pescador",
  "Pianista",
  "Piloto de avión",
  "Pintor",
  "Plomero",
  "Podólogo",
  "Policía",
  "Politólogo",
  "Profesor universitario",
  "Programador",
  "Psicólogo",
  "Publicista",
  "Químico",
  "Radiólogo",
  "Recepcionista",
  "Reparador de electrodomésticos",
  "Reportero",
  "Representante de ventas",
  "Restaurador de arte",
  "Relojero",
  "Sastre",
  "Secretario",
  "Sociólogo",
  "Soldador",
  "Sommelier",
  "Submarinista",
  "Tatuador",
  "Taxista",
  "Tecnólogo en alimentos",
  "Técnico automotriz",
  "Técnico de laboratorio",
  "Técnico de sonido",
  "Técnico electrónico",
  "Técnico en informática",
  "Terapista ocupacional",
  "Terapeuta",
  "Topógrafo",
  "Traductor",
  "Transportista",
  "Urólogo",
  "Vendedor",
  "Veterinario",
  "Videógrafo",
  "Youtuber",
  "Zapatero"
];

export default ocupaciones;
